// Default URLs to auto-ignore
export const DEFAULT_IGNORED_URLS = [
  '*.gov*',
  '*.mil*',
  'gmail.com*',
  'hotmail.com*',
  'mail.*',
  'outlook.com*',
  '*/notifications*',
  '*/messages*',
  'addons.mozilla.org*',
  'brave.com*',
  'chrome.google.com*',
  'chromewebstore.google.com*',
  'microsoft.com*',
  'mozilla.org*',
  'chatgpt.com*',
  '*.ai/*',
  'github.com*'
];

// Default keyword groups (alphabetically ordered)
export const DEFAULT_KEYWORD_GROUPS = {
  'Environmental': [
    'carbon footprint',
    'carbon neutral',
    'carbon offset',
    'carbon tax',
    'carbon trading',
    'climate activist',
    'climate change',
    'climate crisis',
    'climate emergency',
    'climate migration',
    'climate protest',
    'climate refugee',
    'coal plant',
    'deforestation',
    'desertification',
    'eco-anxiety',
    'eco-friendly',
    'environmental impact',
    'environmental justice',
    'extreme heat',
    'flash flood',
    'flooding',
    'fossil fuel',
    'global warming',
    'glacier melt',
    'greenhouse gas',
    'heat wave',
    'hottest year',
    'hurricane',
    'melting ice caps',
    'methane emissions',
    'natural disaster',
    'ozone layer',
    'polar vortex',
    'rising sea levels',
    'sea ice loss',
    'smoke pollution',
    'solar radiation',
    'species extinction',
    'water scarcity',
    'wildfire'
  ],
  'Financial/Economic': [
    'bear market',
    'bull market',
    'Fed rate',
    'Federal Reserve',
    'HODL',
    'inflation',
    'market crash',
    'recession',
    'short squeeze',
    'trading halt',
    'TSLA',
    'Wall Street'
  ],
  'International Political Figures': [
    'Angela Merkel',
    'Benjamin Netanyahu',
    'Boris Johnson',
    'Ebrahim Raisi',
    'Erdogan',
    'Emmanuel Macron',
    'Fumio Kishida',
    'Giorgia Meloni',
    'Imran Khan',
    'Jacinda Ardern',
    'Jair Bolsonaro',
    'Justin Trudeau',
    'Keir Starmer',
    'Kim Jong-un',
    'Lee Hsien Loong',
    'Luis Inácio Lula da Silva',
    'Narendra Modi',
    'Nawaz Sharif',
    'Olaf Scholz',
    'Orbán',
    'Pedro Sánchez',
    'Putin',
    'Recep Tayyip Erdogan',
    'Rishi Sunak',
    'Salman bin Abdulaziz',
    'Sheikh Hasina',
    'Ursula von der Leyen',
    'Volodymyr Zelensky',
    'Xi Jinping',
    'Yoon Suk-yeol'
  ],
  'International Relations': [
    'Afghanistan',
    'air defense system',
    'airstrike',
    'arms deal',
    'arms embargo',
    'arms race',
    'border dispute',
    'ceasefire',
    'claim responsibility',
    'coalition forces',
    'conflict zone',
    'cyber warfare',
    'diplomatic relations',
    'Gaza',
    'Hamas',
    'Hong Kong',
    'human rights violation',
    'IDF',
    'insurgent group',
    'intelligence agency',
    'Iran',
    'Iraq',
    'Israel',
    'Israeli',
    'jihadist',
    'joint military exercise',
    'Middle East',
    'militant',
    'missile defense',
    'missile strike',
    'nuclear arsenal',
    'nuclear proliferation',
    'North Korea',
    'occupation',
    'Palestine',
    'Palestinian',
    'peace talks',
    'proxy war',
    'refugee crisis',
    'revolutionary guard',
    'Russia',
    'Russian',
    'sanctions',
    'Saudi-led coalition',
    'Syria',
    'Taliban',
    'territorial waters',
    'Ukraine',
    'Ukrainian',
    'UN resolution',
    'US foreign policy',
    'war crimes',
    'West Bank',
    'Zionism',
    'Zionist'
  ],
  'Media and Business Figures': [
    'Alex Jones',
    'Anthony Fauci',
    'Ben Shapiro',
    'Bill Gates',
    'Breitbart',
    'Candace Owens',
    'Charlie Kirk',
    'Daily Wire',
    'Dan Bongino',
    'Dave Rubin',
    'David Icke',
    'David Sacks',
    'Elon Musk',
    'Glenn Beck',
    'Howard Stern',
    'InfoWars',
    'Janet Yellen',
    'Jeff Bezos',
    'Joe Rogan',
    'Jordan Peterson',
    'Joy Reid',
    'Kanye West',
    'Laura Ingraham',
    'Lara Logan',
    'Mark Cuban',
    'Mark Zuckerberg',
    'Matt Drudge',
    'Matt Walsh',
    'Michael Knowles',
    'Newsmax',
    'Peter Thiel',
    'Project Veritas',
    'Rachel Maddow',
    'Robert F. Kennedy Jr.',
    'Roger Ailes',
    'Rupert Murdoch',
    'Sean Hannity',
    'Sheryl Sandberg',
    'Steven Crowder',
    'Tim Pool',
    'TPUSA',
    'Tucker Carlson',
    'Turning Point USA',
    'Vivek Ramaswamy'
  ],
  'Political and Government': [
    '1776',
    '2nd Amendment',
    'abortion',
    'ACA',
    'alternative facts',
    'America First',
    'American exceptionalism',
    'Antifa',
    'audit the vote',
    'authoritarian',
    'ballot dump',
    'ballot harvesting',
    'big government',
    'big lie',
    'bipartisanship',
    'black bloc',
    'border crisis',
    'boycott',
    'Brexit',
    'Capitol Hill',
    'CIA',
    'Citizens United',
    'civil liberties',
    'cloture',
    'Communist',
    'Congress',
    'conservative',
    'constitutional carry',
    'dark Brandon',
    'dark money',
    'deep state',
    'Democrat',
    'Democratic',
    'democracy',
    'Dems',
    'Department of Education',
    'Department of Justice',
    'Department of State',
    'Department of the Interior',
    'Department of Treasury',
    'DHS',
    'DOE',
    'DNC',
    'DOJ',
    'dictator',
    'Dominion',
    'drain the swamp',
    'electoral college',
    'election',
    'elected',
    'entitlement reform',
    'executive order',
    'executive privilege',
    'extremist',
    'fake news',
    'faith based',
    'far left',
    'far right',
    'FBI',
    'FCC',
    'FDA',
    'Federal Election Commission',
    'Federal Reserve',
    'Federalist Society',
    'filibuster',
    'FISA',
    'founding fathers',
    'freedom of speech',
    'Freedom Caucus',
    'GOP',
    'government shutdown',
    'Great Awakening',
    'Green New Deal',
    'healthcare',
    'health insurance',
    'Heritage Action',
    'Heritage Foundation',
    'Homeland Security',
    'House Freedom Caucus',
    'House race',
    'House Speaker',
    'House Oversight',
    'House of Representatives',
    'Impeachment',
    'InfoWars',
    'insurrection',
    'Jan 6',
    'J6',
    'Judicial Watch',
    'KKK',
    'Kremlin',
    'Ku Klux Klan',
    'labor unions',
    'left-wing',
    'leftist',
    'legislature',
    'liberal',
    'libertarian',
    'lock her up',
    'lock him up',
    'MAGA',
    'mail-in ballot',
    'mainstream media',
    'mandate',
    'midterm',
    'MSM',
    'nationalist',
    'NATO',
    'neoliberal',
    'neo-Nazi',
    'oligarch',
    'oligarchy',
    'patriot',
    'patriot party',
    'polarization',
    'poll observer',
    'poll watcher',
    'populism',
    'post-election',
    'POTUS',
    'President',
    'Presidency',
    'Presidential',
    'Project 2025',
    'propaganda',
    'public policy',
    'QAnon',
    'radical left',
    'radical right',
    'release the kraken',
    'reproductive rights',
    'Republican',
    'resistance',
    'rightwing',
    'rightist',
    'rigged election',
    'RINO',
    'RNC',
    'RFK',
    'rule of law',
    'sanctuary city',
    'SCOTUS',
    'second amendment',
    'Senate',
    'silent majority',
    'Smartmatic',
    'socialism',
    'socialist',
    'Soros',
    'Squad',
    'states rights',
    'stolen election',
    'stop the steal',
    'Supreme Court',
    'surveillance state',
    'tax reform',
    'Tea Party',
    'term limits',
    'totalitarian',
    'transparency',
    'UN resolution',
    'unconstitutional',
    'voter',
    'voter fraud',
    'voter ID laws',
    'voter suppression',
    'voting machine',
    'Washington elite',
    'White House',
    'WWG1WGA'
  ],
  'Social Issues': [
    '1312',
    'ACAB',
    'age of consent',
    'all lives matter',
    'alt-right',
    'anti-fascist',
    'anti-Semitic',
    'anti-Semitism',
    'anti-woke',
    'back the blue',
    'bias incident',
    'binary gender',
    'birtherism',
    'Black Lives Matter',
    'BLM',
    'blue lives matter',
    'body positivity',
    'Breonna Taylor',
    'Capitol',
    'cancel culture',
    'censorship',
    'citizenship',
    'colorism',
    'cultural appropriation',
    'cultural Marxism',
    'culture war',
    'critical race theory',
    'CRT',
    'defund the police',
    'dehumanization',
    'deportation',
    'digital blackface',
    'disinformation',
    'diversity training',
    'domestic terrorism',
    'DREAMers',
    'equity vs equality',
    'extremism',
    'fascism',
    'fascist',
    'feminism',
    'feminist',
    'food insecurity',
    'free speech zone',
    'gender binary',
    'gender ideology',
    'gender neutral',
    'gender pronouns',
    'gender',
    'George Floyd',
    'gerrymandering',
    'great replacement',
    'groomer',
    'gun control',
    'hate crime',
    'hate group',
    'hate speech',
    'historical trauma',
    'Hitler',
    'identity politics',
    'immigrant rights',
    'implicit bias',
    'income inequality',
    'intersectionality',
    'LGBTQ+ rights',
    'masculinity',
    'microaggression',
    'migrant',
    'minimum wage',
    'misogynist',
    'misogyny',
    'multiculturalism',
    'murdered and missing Indigenous women',
    'Nazi',
    'patriarchy',
    'police brutality',
    'political',
    'politically correct',
    'post-colonialism',
    'pronoun',
    'race baiting',
    'race card',
    'racial profiling',
    'racial sensitivity',
    'racism',
    'racist',
    'rape culture',
    'replacement theory',
    'reverse racism',
    'sexism',
    'sexist',
    'safe space',
    'SJW',
    'slavery',
    'social justice warrior',
    'supremacist',
    'systemic oppression',
    'systemic racism',
    'thin blue line',
    'toxic masculinity',
    'trafficking',
    'trans rights',
    'transgender',
    'transphobia',
    'trigger warning',
    'unconscious bias',
    'virtue signaling',
    'wealth inequality',
    'white nationalist',
    'white privilege',
    'woke',
    'xenophobia',
    'xenophobic',
    'your body my choice',
    'your body, my choice'
  ],
  'Technology': [
    'cyberbully',
    'deepfake',
    'Gab',
    'GETTR',
    'NFT',
    'Parler',
    'Rumble',
    'shadowban',
    'Telegram',
    'TikTok ban',
    'Truth Social',
    'Twitter',
    'verified account',
    'X.com'
  ],
  'US Political Figures': [
    'Aileen Cannon',
    'Alexandria Ocasio-Cortez',
    'AOC',
    'Al Gore',
    'Amy Coney Barrett',
    'Anthony Blinken',
    'Asa Hutchinson',
    'Bernie Sanders',
    'Beto O\'Rourke',
    'Bill Barr',
    'Biden',
    'Blinken',
    'Boebert',
    'Cory Booker',
    'Chris Christie',
    'Clarence Thomas',
    'Dan Crenshaw',
    'DeSantis',
    'Donald J',
    'Don Jr.',
    'Donald Trump Jr.',
    'Trumpism',
    'Doug Burgum',
    'Dianne Feinstein',
    'Dick Cheney',
    'DJT',
    'Elizabeth Warren',
    'Eric Swalwell',
    'Fetterman',
    'Francis Suarez',
    'Gavin Newsom',
    'Giuliani',
    'Glenn Youngkin',
    'Greg Abbott',
    'Hakeem Jeffries',
    'Hillary Clinton',
    'Ilhan Omar',
    'Ivanka',
    'Jack Smith',
    'JD Vance',
    'J.D. Vance',
    'Jim Jordan',
    'Joe Lieberman',
    'Joe Manchin',
    'John Bolton',
    'Josh Hawley',
    'Kamala Harris',
    'VP Harris',
    'Harris campaign',
    'Katie Porter',
    'Kevin McCarthy',
    'Kristi Noem',
    'Larry Elder',
    'Lauren Boebert',
    'Lindsey Graham',
    'Lloyd Austin',
    'Liz Cheney',
    'Manchin',
    'Marjorie',
    'Marjorie Taylor Greene',
    'Mark Milley',
    'Matt Gaetz',
    'Melania',
    'Merrick Garland',
    'Mike Johnson',
    'Mike Lee',
    'Mike Lindell',
    'Mike Pompeo',
    'Mitch McConnell',
    'Mitt Romney',
    'MTG',
    'MyPillow',
    'Nancy Pelosi',
    'Nikki Haley',
    'Obama',
    'Ocasio-Cortez',
    'Pelosi',
    'Pence',
    'Pete Buttigieg',
    'Psaki',
    'Ramaswamy',
    'Rand Paul',
    'Rashida Tlaib',
    'Rick Scott',
    'Robert F. Kennedy Jr.',
    'Roger Stone',
    'Ron DeSantis',
    'Ron Johnson',
    'Sarah Huckabee Sanders',
    'Sidney Powell',
    'Sinema',
    'Stacey Abrams',
    'Steve Bannon',
    'Taylor Greene',
    'Ted Cruz',
    'Tim Scott',
    'Tim Walz',
    'Tom Cotton',
    'Trump',
    'Tulsi Gabbard',
    'Vivek Ramaswamy',
    'Will Hurd'
  ],
  'Violence and Extremism': [
    'active shooter',
    'assassination',
    'attempted murder',
    'bombing',
    'car bomb',
    'civil unrest',
    'conspiracy theory',
    'deadly explosion',
    'domestic extremist',
    'domestic terrorism',
    'ethnic cleansing',
    'extremist group',
    'gunman',
    'AR-15',
    'hate crime',
    'hate group',
    'hoax',
    'honor killing',
    'hostage situation',
    'incendiary device',
    'insurrection',
    'lynching',
    'manifesto',
    'mass casualty',
    'mass shooting',
    'militant',
    'murdered',
    'pipe bomb',
    'radicalization',
    'radicalized',
    'rape',
    'riot',
    'sectarian violence',
    'semiautomatic',
    'serial killer',
    'sexual assault',
    'shooter',
    'stabbing spree',
    'suicide blast',
    'suicide bomber',
    'terror attack',
    'terror cell',
    'terrorism',
    'terrorist group',
    'threat of violence',
    'violent extremist',
    'weapons',
    'whistleblower',
    'white supremacy'
  ],
  'Other': [
    'anti-vaxxer',
    'big government',
    'big pharma',
    'billionaire',
    'censorship',
    'civil liberties',
    'common sense gun laws',
    'conspiracy',
    'conspiracy theory',
    'controlled opposition',
    'crisis actor',
    'cult',
    'deep state',
    'do your own research',
    'DYOR',
    'elite agenda',
    'false flag',
    'freedom of speech',
    'government control',
    'government cover-up',
    'Great Reset',
    'hoax',
    'illuminati',
    'mandate',
    'martial law',
    'medical freedom',
    'microchip implant',
    'plandemic',
    'population control',
    'protest',
    'riot',
    'scamdemic',
    'shadow government',
    'sheeple',
    'social experiment',
    'totalitarian',
    'toxic chemicals',
    'undercover',
    'vaccine',
    'vaccine passport',
    'vaccine side effects',
    'weaponize',
    'world government',
    'woke agenda'
  ],
};
