// Default keyword groups (alphabetically ordered)
// some words look like dupes but this allows for more flexibility in matching
// and unselecting specific keywords
export const DEFAULT_KEYWORD_GROUPS = {
  "Education": [
    "affirmative action",
    "charter school",
    "common core",
    "free college",
    "homeschooling",
    "school choice",
    "school prayer",
    "sex education",
    "standardized testing",
    "student loan",
    "teachers union"
  ],

  "Environment and Climate Change": [
    "carbon emissions",
    "carbon footprint",
    "carbon neutral",
    "carbon offset",
    "carbon tax",
    "carbon trading",
    "climate action",
    "climate activist",
    "climate change",
    "climate crisis",
    "climate denier",
    "climate emergency",
    "climate migration",
    "climate protest",
    "climate refugee",
    "climate science",
    "coal plant",
    "deforestation",
    "desertification",
    "eco-anxiety",
    "eco-friendly",
    "environmental impact",
    "environmental justice",
    "extreme heat",
    "flash flood",
    "flooding",
    "fossil fuels",
    "glacier melt",
    "global warming",
    "Green New Deal",
    "greenhouse gas",
    "heat wave",
    "hottest year",
    "hurricane",
    "melting ice caps",
    "methane emissions",
    "natural disaster",
    "ozone layer",
    "Paris Agreement",
    "polar vortex",
    "renewable energy",
    "rising sea levels",
    "sea ice loss",
    "sea level rise",
    "smoke pollution",
    "solar radiation",
    "species extinction",
    "tariff",
    "water scarcity",
    "wildfire"
  ],

  "Financial/Economic": [
    "bear market",
    "bull market",
    "Fed rate",
    "Federal Reserve",
    "HODL",
    "inflation",
    "market crash",
    "recession",
    "short squeeze",
    "trading halt",
    "TSLA",
    "Wall Street"
  ],

  "Gun Rights": [
    "assault weapon",
    "background check",
    "concealed carry",
    "ghost gun",
    "gun control",
    "gun rights",
    "mass shooting",
    "NRA",
    "open carry",
    "red flag law",
    "school shooting",
    "Second Amendment"
  ],

  "Immigration": [
    "amnesty",
    "asylum seeker",
    "border wall",
    "DACA",
    "deportation",
    "Dreamers",
    "ICE",
    "illegal alien",
    "migrant caravan",
    "refugee",
    "sanctuary city",
    "undocumented"
  ],

  "International Political Figures": [
    "Angela Merkel",
    "Benjamin Netanyahu",
    "Boris Johnson",
    "Ebrahim Raisi",
    "Emmanuel Macron",
    "Erdogan",
    "Fumio Kishida",
    "Giorgia Meloni",
    "Imran Khan",
    "Jacinda Ardern",
    "Jair Bolsonaro",
    "Justin Trudeau",
    "Keir Starmer",
    "Kim Jong-un",
    "Lee Hsien Loong",
    "Luis Inácio Lula da Silva",
    "Narendra Modi",
    "Nawaz Sharif",
    "Olaf Scholz",
    "Orbán",
    "Pedro Sánchez",
    "Putin",
    "Recep Tayyip Erdogan",
    "Rishi Sunak",
    "Salman bin Abdulaziz",
    "Sheikh Hasina",
    "Ursula von der Leyen",
    "Volodymyr Zelensky",
    "Xi Jinping",
    "Yoon Suk-yeol"
  ],

  "International Relations": [
    "Afghanistan",
    "air defense system",
    "airstrike",
    "arms deal",
    "arms embargo",
    "arms race",
    "border dispute",
    "border czar",
    "border tsar",
    "ceasefire",
    "claim responsibility",
    "coalition forces",
    "conflict zone",
    "cyber warfare",
    "diplomatic relations",
    "Gaza",
    "Hamas",
    "hardliner",
    "Hong Kong",
    "human rights violation",
    "IDF",
    "insurgent group",
    "intelligence agency",
    "Iran",
    "Iraq",
    "Israel",
    "Israeli",
    "jihadist",
    "joint military exercise",
    "Middle East",
    "militant",
    "missile defense",
    "missile strike",
    "nuclear arsenal",
    "nuclear proliferation",
    "North Korea",
    "occupation",
    "Palestine",
    "Palestinian",
    "peace talks",
    "proxy war",
    "refugee crisis",
    "revolutionary guard",
    "Russia",
    "Russian",
    "sanctions",
    "Saudi-led coalition",
    "Syria",
    "Taliban",
    "territorial waters",
    "Ukraine",
    "Ukrainian",
    "UN resolution",
    "US foreign policy",
    "war crimes",
    "West Bank",
    "Zionism",
    "Zionist"
  ],

  "LGBTQ": [
    "bisexual",
    "coming out",
    "conversion therapy",
    "Don't Say Gay",
    "drag queen",
    "gay",
    "gender dysphoria",
    "gender identity",
    "gender-neutral",
    "lesbian",
    "LGBT",
    "LGBTQ",
    "non-binary",
    "pride flag",
    "Pride Month",
    "pride parade",
    "queer",
    "Respect for Marriage Act",
    "same-sex marriage",
    "transgender"
  ],

  "Media Figures": [
    "Alex Jones",
    "Anderson Cooper",
    "Ben Shapiro",
    "Bill Maher",
    "Candace Owens",
    "Chris Cuomo",
    "Don Lemon",
    "Glenn Greenwald",
    "Joe Rogan",
    "Jordan Peterson",
    "Joy Reid",
    "Laura Ingraham",
    "Michael Knowles",
    "Rachel Maddow",
    "Sean Hannity",
    "Steven Crowder",
    "Tomi Lahren",
    "Tucker Carlson"
  ],

  "Other": [
    "anti-vaxxer",
    "big government",
    "big pharma",
    "billionaire",
    "censorship",
    "civil liberties",
    "common sense gun laws",
    "conspiracy",
    "conspiracy theory",
    "controlled opposition",
    "crisis actor",
    "cult",
    "deep state",
    "do your own research",
    "DYOR",
    "elite agenda",
    "false flag",
    "freedom of speech",
    "government control",
    "government cover-up",
    "Great Reset",
    "hoax",
    "illuminati",
    "mandate",
    "martial law",
    "medical freedom",
    "microchip implant",
    "misinformation",
    "plandemic",
    "population control",
    "protest",
    "riot",
    "scamdemic",
    "shadow government",
    "sheeple",
    "social experiment",
    "surveillance state",
    "tech bro",
    "totalitarian",
    "toxic chemicals",
    "undercover",
    "vaccine",
    "vaccine passport",
    "vaccine side effects",
    "weaponize",
    "world government",
    "woke agenda"
  ],

  "Political and Government": [
    "1776",
    "2nd Amendment",
    "abortion",
    "ACA",
    "alternative facts",
    "America First",
    "American exceptionalism",
    "Antifa",
    "audit the vote",
    "authoritarian",
    "ballot",
    "big government",
    "big lie",
    "bipartisanship",
    "black bloc",
    "blue wave",
    "border crisis",
    "boycott",
    "Brexit",
    "Capitol Hill",
    "CIA",
    "Citizens United",
    "civil liberties",
    "Communist",
    "Congress",
    "conservative",
    "constitutional carry",
    "dark Brandon",
    "dark money",
    "deep state",
    "Democrat",
    "Democratic",
    "democracy",
    "Dems",
    "Department of Education",
    "Department of Justice",
    "Department of State",
    "Department of the Interior",
    "Department of Treasury",
    "DHS",
    "dictator",
    "DOE",
    "DOJ",
    "Dominion",
    "DNC",
    "drain the swamp",
    "elected",
    "election",
    "electoral college",
    "entitlement reform",
    "executive order",
    "executive privilege",
    "extremist",
    "faith based",
    "fake news",
    "far left",
    "far right",
    "FBI",
    "FCC",
    "FDA",
    "Federal Election Commission",
    "Federal Reserve",
    "Federalist Society",
    "federal judge",
    "filibuster",
    "FISA",
    "founding fathers",
    "freedom of speech",
    "Freedom Caucus",
    "GOP",
    "government shutdown",
    "Great Awakening",
    "Green New Deal",
    "health insurance",
    "healthcare",
    "Heritage Action",
    "Heritage Foundation",
    "Homeland Security",
    "House Freedom Caucus",
    "House Oversight",
    "House race",
    "House Speaker",
    "House of Representatives",
    "Impeachment",
    "InfoWars",
    "insurrection",
    "J6",
    "Jan 6",
    "Judicial Watch",
    "KKK",
    "Kremlin",
    "Ku Klux Klan",
    "labor unions",
    "landslide",
    "lawmaker",
    "left-wing",
    "lead investigator",
    "leftist",
    "legislature",
    "liberal",
    "libertarian",
    "lock her up",
    "lock him up",
    "MAGA",
    "mail-in ballot",
    "mainstream media",
    "mandate",
    "Mar-a-Lago",
    "middle class",
    "midterm",
    "MSM",
    "nationalist",
    "NATO",
    "neoliberal",
    "neo-Nazi",
    "oligarch",
    "oligarchy",
    "patriot",
    "patriot party",
    "polarization",
    "poll observer",
    "poll watcher",
    "populism",
    "post-election",
    "POTUS",
    "Presidency",
    "President",
    "Presidential",
    "Project 2025",
    "propaganda",
    "public policy",
    "QAnon",
    "radical",
    "radical left",
    "radical right",
    "red wave",
    "reforms",
    "release the kraken",
    "reproductive rights",
    "Republican",
    "resistance",
    "RFK",
    "rightwing",
    "rightist",
    "rigged election",
    "RINO",
    "RNC",
    "rule of law",
    "sanctuary city",
    "SCOTUS",
    "second amendment",
    "Secretary of Defense",
    "Secretary of Education",
    "Secretary of State",
    "Secretary of the Interior",
    "Secretary of the Treasury",
    "Senate",
    "Senator",
    "shifting right",
    "silent majority",
    "Smartmatic",
    "socialism",
    "socialist",
    "Soros",
    "Squad",
    "states rights",
    "stolen election",
    "stop the steal",
    "Supreme Court",
    "tax reform",
    "Tea Party",
    "term limits",
    "totalitarian",
    "trade war",
    "transparency",
    "unconstitutional",
    "UN resolution",
    "US Postal",
    "USPS",
    "voter",
    "voter ID laws",
    "voter fraud",
    "voter suppression",
    "voting machine",
    "Washington elite",
    "White House",
    "working class",
    "WWG1WGA"
  ],

  "Political Ideologies": [
    "alt-right",
    "anarchism",
    "antifa",
    "communism",
    "conservatism",
    "far-left",
    "far-right",
    "fascism",
    "libertarianism",
    "liberalism",
    "Marxism",
    "neo-Nazism",
    "populism",
    "progressivism",
    "radical left",
    "radical right",
    "socialism",
    "white nationalism"
  ],

  "Race Relations": [
    "affirmative action",
    "Black Lives Matter",
    "BLM",
    "critical race theory",
    "CRT",
    "cultural appropriation",
    "diversity quota",
    "hate crime",
    "mass incarceration",
    "microaggression",
    "police brutality",
    "race card",
    "racial bias",
    "racial discrimination",
    "racial equality",
    "racial equity",
    "racial justice",
    "racial profiling",
    "systemic racism",
    "white privilege",
    "white supremacy"
  ],

  "Reproductive Health": [
    "abortion",
    "birth control",
    "crisis pregnancy center",
    "maternal mortality",
    "Planned Parenthood",
    "pro-choice",
    "pro-life",
    "Roe v Wade"
  ],

  "Social Issues": [
    "1312",
    "ACAB",
    "age of consent",
    "all lives matter",
    "alt-right",
    "anti-fascist",
    "anti-Semitic",
    "anti-Semitism",
    "anti-woke",
    "back the blue",
    "bias incident",
    "binary gender",
    "birtherism",
    "Black Lives Matter",
    "BLM",
    "blue lives matter",
    "body positivity",
    "Breonna Taylor",
    "cancel culture",
    "Capitol",
    "censorship",
    "citizenship",
    "colorism",
    "confederate",
    "crackdown",
    "critical race theory",
    "CRT",
    "cultural appropriation",
    "cultural Marxism",
    "culture war",
    "defund the police",
    "dehumanization",
    "deportation",
    "digital blackface",
    "disinformation",
    "diversity training",
    "domestic terrorism",
    "DREAMers",
    "equity vs equality",
    "extremism",
    "fascism",
    "fascist",
    "feminism",
    "feminist",
    "food insecurity",
    "free speech zone",
    "gender",
    "gender binary",
    "gender ideology",
    "gender neutral",
    "gender pronouns",
    "George Floyd",
    "gerrymandering",
    "great replacement",
    "groomer",
    "gun control",
    "hate crime",
    "hate group",
    "hate speech",
    "historical trauma",
    "Hitler",
    "identity politics",
    "immigrant rights",
    "immigration",
    "implicit bias",
    "income inequality",
    "intersectionality",
    "LGBTQ+ rights",
    "masculinity",
    "microaggression",
    "migrant",
    "minimum wage",
    "misogynist",
    "misogyny",
    "multiculturalism",
    "murdered and missing Indigenous women",
    "Nazi",
    "patriarchy",
    "police brutality",
    "political",
    "politically correct",
    "post-colonialism",
    "pronoun",
    "race baiting",
    "race card",
    "racial profiling",
    "racial sensitivity",
    "racism",
    "racist",
    "rape culture",
    "replacement theory",
    "reverse racism",
    "safe space",
    "sexism",
    "sexist",
    "SJW",
    "slavery",
    "social justice warrior",
    "supremacist",
    "systemic oppression",
    "systemic racism",
    "thin blue line",
    "toxic masculinity",
    "trafficking",
    "trans rights",
    "transgender",
    "transphobia",
    "trigger warning",
    "unconscious bias",
    "virtue signaling",
    "wealth inequality",
    "white nationalist",
    "white privilege",
    "woke",
    "xenophobia",
    "xenophobic",
    "your body my choice",
    "your body, my choice"
  ],

  "Technology": [
    "cyberbully",
    "deepfake",
    "Gab",
    "GETTR",
    "NFT",
    "Parler",
    "Rumble",
    "shadowban",
    "Telegram",
    "TikTok ban",
    "Truth Social",
    "Twitter",
    "verified account",
    "X.com"
  ],

  "US Political Figures - Full Name": [
    "Al Gore",
    "Alexandria Ocasio-Cortez",
    "Amy Coney Barrett",
    "Amy Klobuchar",
    "Anthony Blinken",
    "Asa Hutchinson",
    "Bernie Sanders",
    "Beto O'Rourke",
    "Bill Barr",
    "Brian Kemp",
    "Chris Christie",
    "Chuck Schumer",
    "Clarence Thomas",
    "Cory Booker",
    "Dan Crenshaw",
    "Dianne Feinstein",
    "Dick Cheney",
    "Donald Trump",
    "Donald Trump Jr.",
    "Doug Burgum",
    "Elizabeth Warren",
    "Elise Stefanik",
    "Eric Swalwell",
    "Francis Suarez",
    "Gavin Newsom",
    "George Santos",
    "Glenn Youngkin",
    "Greg Abbott",
    "Gretchen Whitmer",
    "Hakeem Jeffries",
    "Herschel Walker",
    "Hillary Clinton",
    "Ilhan Omar",
    "J.D. Vance",
    "JD Vance",
    "Jim Jordan",
    "Joe Biden",
    "Joe Lieberman",
    "Joe Manchin",
    "John Bolton",
    "John Oliver",
    "Josh Hawley",
    "Kamala Harris",
    "Katie Porter",
    "Kevin McCarthy",
    "Kristi Noem",
    "Kyrsten Sinema",
    "Larry Elder",
    "Lauren Boebert",
    "Lindsey Graham",
    "Liz Cheney",
    "Lloyd Austin",
    "Marjorie Taylor Greene",
    "Mark Milley",
    "Matt Gaetz",
    "Merrick Garland",
    "Mike Johnson",
    "Mike Lee",
    "Mike Lindell",
    "Mike Pence",
    "Mike Pompeo",
    "Mitch McConnell",
    "Mitt Romney",
    "Nancy Pelosi",
    "Nikki Haley",
    "Pete Buttigieg",
    "Rand Paul",
    "Raphael Warnock",
    "Rashida Tlaib",
    "Rick Scott",
    "Robert F. Kennedy Jr.",
    "Roger Stone",
    "Ron DeSantis",
    "Ron Johnson",
    "Sarah Huckabee Sanders",
    "Sidney Powell",
    "Stacey Abrams",
    "Steve Bannon",
    "Ted Cruz",
    "Tim Scott",
    "Tim Walz",
    "Tom Cotton",
    "Tulsi Gabbard",
    "Vivek Ramaswamy",
    "Will Hurd"
  ],

  "US Political Figures - Single Name": [
    "Abrams",
    "AOC",
    "Biden",
    "Blinken",
    "Boebert",
    "Booker",
    "Buttigieg",
    "Cheney",
    "Clinton",
    "DeSantis",
    "Elon",
    "Fetterman",
    "Feinstein",
    "Gaetz",
    "Giuliani",
    "Gore",
    "Hawley",
    "Ilhan",
    "Ivanka",
    "Kemp",
    "Kennedy",
    "Klobuchar",
    "Manchin",
    "McConnell",
    "Melania",
    "Musk",
    "Newsom",
    "Noem",
    "Obama",
    "Ocasio-Cortez",
    "Pelosi",
    "Pence",
    "Ramaswamy",
    "Romney",
    "Schumer",
    "Sinema",
    "Stefanik",
    "Suarez",
    "Swalwell",
    "Tlaib",
    "Trump",
    "Vance",
    "Warnock",
    "Whitmer",
    "Youngkin"
  ],
  "Vaccine Controversies": [
    "Andrew Wakefield",
    "anti-vaxxer",
    "autism",
    "Big Pharma",
    "Covid-19 vaccine",
    "herd immunity",
    "HPV vaccine",
    "Jenny McCarthy",
    "vaccination",
    "measles outbreak",
    "medical freedom",
    "MMR vaccine",
    "polio",
    "religious exemption",
    "thimerosal",
    "vaccine"
  ],
  "Violence and Extremism": [
    "active shooter",
    "AR-15",
    "assassination",
    "attempted murder",
    "bombing",
    "car bomb",
    "civil unrest",
    "deadly explosion",
    "domestic extremist",
    "domestic terrorism",
    "ethnic cleansing",
    "extremist group",
    "gunman",
    "hate crime",
    "hate group",
    "hoax",
    "honor killing",
    "hostage situation",
    "incendiary device",
    "insurrection",
    "lynching",
    "manifesto",
    "mass casualty",
    "militant",
    "murdered",
    "pipe bomb",
    "radicalization",
    "radicalized",
    "rape",
    "riot",
    "sectarian violence",
    "semiautomatic",
    "serial killer",
    "sexual assault",
    "shooter",
    "stabbing spree",
    "suicide blast",
    "suicide bomber",
    "terror attack",
    "terror cell",
    "terrorism",
    "terrorist group",
    "threat of violence",
    "violent extremist",
    "weapons",
    "whistleblower"
  ]
};

// Function to determine matching option based on keyword length
export function getMatchingOption(keyword) {
  return keyword.length <= 3 ? 'exact' : 'flexible';
}
