name: Trending news

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install and cache PowerShell modules
        uses: potatoqualitee/psmodulecache@v6.0
        with:
          modules-to-cache: PSOpenAI

      - name: Run news update script
        shell: pwsh
        env:
          BRAVE_API_KEY: ${{ secrets.BRAVE_API_KEY }}
          GIST_PAT: ${{ secrets.GIST_PAT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
          BING_API_KEY: ${{ secrets.BING_API_KEY }}
        run: |
          ./.github/workflows/update-news-gist.ps1